asset: woorl
tap: homebrew-tap/Formula/woorl.rb
template: |
  class Woorl < Formula
    desc     "$REPO_DESCRIPTION"
    homepage "$REPO_WEBSITE"
    version  "$STABLE_VERSION"
    url      "$STABLE_ASSET_URL"
    sha256   "$STABLE_ASSET_SHA256"
    license  "Apache-2.0"

    depends_on "erlang"

    def install
      bin.install "woorl"
    end

    test do
      system "#{bin}/woorl"
    end
  end