name: Build and release
on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - "[0-9].*"

env:
  ASSETS: |
    woorl-test-linux-amd64.tar.gz
    woorl-test-darwin-arm64.tar.gz

jobs:
  escript:
    runs-on: ubuntu-latest
    container: erlang:23
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build escript
        run: rebar3 escriptize
      - name: Make dist
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir dist
          for asset in $ASSETS; do tar -czvf dist/$asset -C _build/default/bin/ woorl; done
      - name: Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
