name: Build and release
on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - "[0-9].*"

jobs:
  escript:
    runs-on: ubuntu-latest
    container: erlang:28
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Build escript
        run: rebar3 escriptize
      - name: Make dist
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: mkdir dist && tar -czvf dist/woorl-${{ github.ref_name }}.tar.gz -C _build/default/bin/ woorl woorl-json
      - name: Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/*
